### ISSUE TITLE
NameError: name 'get_single_object_tracker' is not defined

### ISSUE THREAD

**Issue by anilesec** [hassony2/homan#3]
Hello @hassony2 

Thanks for making the code available.
I was trying to run the demo. I got the following error:
![image](https://user-images.githubusercontent.com/23581858/137625683-5b6724b6-f82d-47c1-815e-d0fdd68bf62b.png)

And when I check the code there is no class/function with name  "get_single_object_tracker()".

**Comment by anilesec** [comment]
downgrade motpy to version 0.0.9. it will solve the problem. @hassony2  I think it's worth updating in environment.yml

**Comment by hassony2** [comment]
Thank you for the comment !
I updated environment.yml accordingly :)
